# Generated by Django 3.2.16 on 2023-08-04 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_ticket', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies_ticket.movie'),
        ),
    ]
