# Generated by Django 3.2.16 on 2023-08-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_ticket', '0004_theater_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='movie',
        ),
        migrations.CreateModel(
            name='MovieTheaterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_ticket.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_ticket.theater')),
            ],
        ),
        migrations.AddField(
            model_name='theater',
            name='movies',
            field=models.ManyToManyField(through='movies_ticket.MovieTheaterRelationship', to='movies_ticket.Movie'),
        ),
    ]
