# Generated by Django 3.2.16 on 2023-08-05 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_ticket', '0005_auto_20230804_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='movies',
        ),
        migrations.AddField(
            model_name='theater',
            name='movies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies_ticket.movie'),
        ),
        migrations.DeleteModel(
            name='MovieTheaterRelationship',
        ),
    ]
