# Generated by Django 3.2.16 on 2023-08-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_ticket', '0006_auto_20230805_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='movies',
        ),
    ]
