# Generated by Django 3.2.16 on 2023-08-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_ticket', '0008_seat_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(blank=True, null=True, to='movies_ticket.Seat'),
        ),
    ]
